---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jasper9/innkeeper2-worker
params:
  TILE1_SPEC:
    
inputs:
  - name: pipeline-factory
  - name: template


outputs:
  - name: generated-config 



run:
  path: python3.6
  args:
  - ./pipeline-factory/jobs/create-config-job/create-config-task/create-config.py
