---
pipeline_params: &pipeline_params
  INPUT_SPEC: ((input_spec))


resources:

- name: auth
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    bucket: ((s3.buckets.auth))
    region_name: ((s3.region_name))
    secret_access_key: ((s3.secret_access_key))
    endpoint: ((s3.endpoint))
    versioned_file: auth.yml

#- name: pipeline-factory
#  type: git
#  source:
#    uri: https://github.com/jasper9/pipeline-factory.git
#    branch: master



jobs:

- name: get-started-job
  max_in_flight: 1
  plan:
  - get: auth
  - task: get-started-task
    file: pipeline-factory/jobs/get-started-job/get-started-task/get-started-task.yml
    params: *pipeline_params