---

#pipeline_params: &pipeline_params
#  INPUT_SPEC: ((input_spec))



resources:

- name: auth
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    bucket: ((s3.bucket))
    secret_access_key: ((s3.secret_access_key))
    endpoint: ((s3.endpoint))
    skip_ssl_verification: ((s3.skip_ssl_verification))
    use_v2_signing: ((s3.use_v2_signing))
    regexp: auth-(.*).yml

- name: pcf-automation-tasks
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    bucket: ((s3.bucket))
    secret_access_key: ((s3.secret_access_key))
    endpoint: ((s3.endpoint))
    skip_ssl_verification: ((s3.skip_ssl_verification))
    use_v2_signing: ((s3.use_v2_signing))
    regexp: tasks-(.*).zip

- name: pcf-automation-image
  type: s3
  source:
    access_key_id: ((s3.access_key_id))
    bucket: ((s3.bucket))
    secret_access_key: ((s3.secret_access_key))
    endpoint: ((s3.endpoint))
    skip_ssl_verification: ((s3.skip_ssl_verification))
    use_v2_signing: ((s3.use_v2_signing))
    regexp: image-(.*).tar

- name: pipeline-factory
  type: git
  source:
    uri: https://github.com/jasper9/pipeline-factory.git
    branch: master



jobs:


- name: export-job
  plan:
  - aggregate:  
    - get: auth
    - get: pipeline-factory
    - get: pcf-automation-tasks
      params:
        unpack: true
    - get: pcf-automation-image
      params:
        unpack: true
  - put: auth
    params:
      file: auth/auth-1.yml 
  - task: export-installation
    image: pcf-automation-image
    file: pcf-automation-tasks/tasks/export-installation.yml
    params:
      AUTH_CONFIG_FILE: auth/auth-1.yml

