resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final




resources:
  
- name: pas-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: elastic-runtime
    product_version: ((pas_version))
    sort_by: semver

- name: healthwatch-product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: p-healthwatch
    product_version: ((healthwatch_version))
    sort_by: semver

- name: opsman-image
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ops-manager
    product_version: 2\.1+\.[0-9]+$
    sort_by: semver


jobs:

- name: get-pas-product
  plan:
  - get: pas-product
    params:
      globs: ["cf*.pivotal"]
    trigger: true
  - get: auth
  - put: pas-product-s3
    params:
      file: pas-product/cf-*.pivotal
  - put: auth
    params:
      file: auth/auth.yml

- name: get-healthwatch-product
  plan:
  - get: healthwatch-product
    params:
      globs: ["p-healthwatch*.pivotal"]
    trigger: true
  - get: auth
  - put: healthwatch-product-s3
    params:
      file: healthwatch-product/p-healthwatch-*.pivotal
  - put: auth
    params:
      file: auth/auth.yml

- name: get-opsman-image
  plan:
  - get: opsman-image
    params:
      globs: ["*.ova", "*.yml"]
    trigger: true
  - get: auth
  - put: opsman-image-s3
    params:
      file: opsman-image/((opsman_image_wildcard))
  - put: auth
    params:
      file: auth/auth.yml
