---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: jasper9/innkeeper2-worker

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  pivnet_token:
  IAAS:
    
inputs:
  - name: pipeline-factory
  - name: p-healthwatch-s3
  - name: nsx-t-ci-pipeline

run:
  path: pipeline-factory/tasks/resolve-stemcell/resolve-stemcell.sh
